shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - prisma@7.10.0

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.5'

packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  workerd: true
