import type { Connect } from 'vite';
import type { Plugin } from 'vite';

import crypto from 'node:crypto';
import fsPromises from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const HASH_LENGTH = 4;
const HASHED_STEM = /^(.+)\.([a-f0-9]{4})$/i;
const HASHED_URL = /^\/(icons|images)\/(.+)\.([a-f0-9]{4})\.([a-z0-9]+)$/i;
const ASSET_DIRS = ['icons', 'images'] as const;

const MIME_BY_EXT: Record<string, string> = {
  '.svg': 'image/svg+xml',
  '.webp': 'image/webp',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.avif': 'image/avif',
};

type AssetDir = (typeof ASSET_DIRS)[number];
type AssetMap = Record<string, string>;
type AssetManifest = Record<AssetDir, AssetMap>;

type AssetManifestPluginOptions = {
  outFile?: string;
};

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fsPromises.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function hashBuffer(buffer: Buffer): string {
  return crypto.createHash('sha256').update(buffer).digest('hex').slice(0, HASH_LENGTH);
}

async function readHash(filePath: string): Promise<{ buffer: Buffer; hash: string }> {
  const buffer = await fsPromises.readFile(filePath);
  return { buffer, hash: hashBuffer(buffer) };
}

function mimeType(ext: string): string {
  return MIME_BY_EXT[ext.toLowerCase()] ?? 'application/octet-stream';
}

function toObjectLiteral(map: AssetMap): string {
  return Object.keys(map)
    .sort((left, right) => left.localeCompare(right))
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])},`)
    .join('\n');
}

async function scanAssetDir(publicRoot: string, dir: AssetDir): Promise<AssetMap> {
  const folder = path.join(publicRoot, dir);
  if (!(await pathExists(folder))) {
    return {};
  }

  const manifest: AssetMap = {};

  for (const fileName of await fsPromises.readdir(folder)) {
    const filePath = path.join(folder, fileName);
    const fileStat = await fsPromises.stat(filePath);
    if (!fileStat.isFile()) {
      continue;
    }

    const extension = path.extname(fileName);
    const stem = path.basename(fileName, extension);
    if (HASHED_STEM.test(stem)) {
      continue;
    }

    const { hash } = await readHash(filePath);
    manifest[stem] = `${dir}/${stem}.${hash}${extension}`;
  }

  return manifest;
}

async function buildManifest(publicRoot: string): Promise<AssetManifest> {
  const [icons, images] = await Promise.all([
    scanAssetDir(publicRoot, 'icons'),
    scanAssetDir(publicRoot, 'images'),
  ]);

  return { icons, images };
}

function renderManifestModule(manifest: AssetManifest): string {
  return `/* eslint-disable */
/* Auto-generated by vite/asset-manifest-plugin.ts — do not edit. */

export const ICONS = {
${toObjectLiteral(manifest.icons)}
} as const;

export const IMAGES = {
${toObjectLiteral(manifest.images)}
} as const;

export type IconId = keyof typeof ICONS;
export type ImageId = keyof typeof IMAGES;

function withBase(assetPath: string): string {
  return \`\${import.meta.env.BASE_URL}\${assetPath}\`;
}

export function iconUrl(id: IconId): string;
export function iconUrl(id: string): string;
export function iconUrl(id: string): string {
  const assetPath = ICONS[id as IconId];
  if (assetPath === undefined) {
    throw new Error(\`Unknown icon: \${id}\`);
  }
  return withBase(assetPath);
}

export function imageUrl(id: ImageId): string;
export function imageUrl(id: string): string;
export function imageUrl(id: string): string {
  const assetPath = IMAGES[id as ImageId];
  if (assetPath === undefined) {
    throw new Error(\`Unknown image: \${id}\`);
  }
  return withBase(assetPath);
}
`;
}

async function writeHashedAssets(publicRoot: string, outRoot: string, manifest: AssetManifest) {
  await Promise.all(
    ASSET_DIRS.map(async (dir) => {
      const targetDir = path.join(outRoot, dir);
      await fsPromises.mkdir(targetDir, { recursive: true });

      await Promise.all(
        Object.entries(manifest[dir]).map(async ([name, hashedPath]) => {
          const extension = path.extname(hashedPath);
          await fsPromises.copyFile(
            path.join(publicRoot, dir, `${name}${extension}`),
            path.join(outRoot, hashedPath),
          );
        }),
      );
    }),
  );
}

async function removePlainPublicCopies(outRoot: string) {
  for (const dir of ASSET_DIRS) {
    const folder = path.join(outRoot, dir);
    if (!(await pathExists(folder))) {
      continue;
    }

    for (const fileName of await fsPromises.readdir(folder)) {
      const filePath = path.join(folder, fileName);
      const fileStat = await fsPromises.stat(filePath);
      if (!fileStat.isFile()) {
        continue;
      }

      const stem = path.basename(fileName, path.extname(fileName));
      if (HASHED_STEM.test(stem)) {
        continue;
      }

      await fsPromises.unlink(filePath);
    }
  }
}

function createDevAssetMiddleware(publicRoot: string): Connect.NextHandleFunction {
  return (req, res, next) => {
    const pathname = req.url?.split('?')[0] ?? '';
    const match = HASHED_URL.exec(pathname);
    if (match === null) {
      next();
      return;
    }

    const [, dir, name, hash, ext] = match;
    const sourcePath = path.join(publicRoot, dir, `${name}.${ext}`);

    void (async () => {
      try {
        if (!(await pathExists(sourcePath))) {
          next();
          return;
        }

        const { buffer, hash: actualHash } = await readHash(sourcePath);
        if (actualHash !== hash.toLowerCase()) {
          next();
          return;
        }

        res.statusCode = 200;
        res.setHeader('Content-Type', mimeType(`.${ext}`));
        res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        res.end(buffer);
      } catch (error) {
        next(error);
      }
    })();
  };
}

export function assetManifestPlugin(options: AssetManifestPluginOptions = {}): Plugin {
  const outFile = options.outFile ?? 'src/generated/asset-urls.ts';

  let root = process.cwd();
  let publicRoot = '';
  let outDir = 'dist';
  let isBuild = false;
  let manifest: AssetManifest = { icons: {}, images: {} };

  return {
    name: 'asset-manifest',
    configResolved: (config) => {
      root = config.root;
      publicRoot = config.publicDir;
      outDir = path.join(root, config.build.outDir);
      isBuild = config.command === 'build';
    },
    buildStart: async () => {
      manifest = await buildManifest(publicRoot);
      const outPath = path.join(root, outFile);
      await fsPromises.mkdir(path.dirname(outPath), { recursive: true });
      await fsPromises.writeFile(outPath, renderManifestModule(manifest));
    },
    configureServer: (server) => {
      server.middlewares.use(createDevAssetMiddleware(publicRoot));
    },
    closeBundle: async () => {
      if (!isBuild) {
        return;
      }

      await writeHashedAssets(publicRoot, outDir, manifest);
      await removePlainPublicCopies(outDir);
    },
  };
}
