name: Deploy API

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @railway/cli
      - run: railway redeploy --service selfskills-api -y
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
